### ISSUE TITLE
Data Ingest Board + Missing `Has-Metadata` Column

### ISSUE THREAD

**Issue by bhonick** [sennetconsortium/ingest-api#169]
Hi @maxsibilla , I noticed a minor area for enhancement in both the HuBMAP and SenNet Data Ingest Boards today. Here is the link to the HuBMAP issue with more details: https://github.com/hubmapconsortium/data-ingest-board/issues/92. Thanks!

**Comment by maxsibilla** [comment]
Coordinate with Derek (working on the HM Ingest API side) and Jes (working on the data ingest board)
