### ISSUE TITLE
Test if Ingest API's latest branch with Ingest Validation Tools work with Cedar for Sample metadata

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/ingest-api#173]
Link to all of the latest Cedar specs:
https://software.docs.hubmapconsortium.org/metadata

Sample Block:
https://hubmapconsortium.github.io/ingest-validation-tools/sample-block/current/

Sample Section:
https://hubmapconsortium.github.io/ingest-validation-tools/sample-section/current/

Sample Suspension:
https://hubmapconsortium.github.io/ingest-validation-tools/sample-suspension/current/

**Comment by maxsibilla** [comment]
We have ported over the latest Cedar additions in Ingest Validation Tools into the SenNet fork and pulled that into Ingest API. We need to 

1.  Verify that this setup supports validating the latest Cedar spec
2. Determine what needs to be done to support validating cedar metadata in the portal

**Comment by libpitt** [comment]
https://github.com/sennetconsortium/ingest-validation-tools/issues/20

**Comment by libpitt** [comment]
@maxsibilla 

## Findings:
If looks like CEDAR is using `validate_upload.py`. The difference is that `validate_upload.py` validates an entire directory, whereas `validate_tsv.py`, as its name suggests is for single TSV file validation.
(Ideally, the `validate_upload.py` file should have been called `validate_directory.py` just so it coincides with `validate_tsv.py`, though not important for functionality)

#### Supporting CEDAR from SN's ingest-api and portal:
1. Our `/metadata/validate` endpoint and process contains the logic in `main()` of `validate_tsv.py`. In `ingest-api.*.validation.validate_tsv()`, we are calling [get_tsv_errors](https://github.com/sennetconsortium/ingest-api/blob/23c90e5b90b7f4490ae02c86dad346b42b52ce34/src/routes/validation/validation.py#L108) of the  Ingest Validation Tools (IVT) submodule. In this method, there is a new parameter, `cedar_api_key`, where we can pass a cedar api key (to be stored in `app.cfg`). 

2. From the portal end, we would probably just need the user to select either _CEDAR_ or _v1_ validation type for their TSV upload. Our `ingest-api.*.validation.determine_schema(entity_type, sub_type)` needs updating to correctly determine the schema name based on the type of validation (_CEDAR_ or _v1_). `get_tsv_errors` requires this `schema_name` param.

### Other / outside of task scope:
#### To support CEDAR with `validate_tsv.py` from within the IVT repo itself:**
It looks like the `validate_tsv.py` needs the updates to the `make_parser()` and `main()` that are currently in `validate_upload.py` to allow support for CEDAR and its required arguments like `--cedar_api_key` and `--globus_token`

**Comment by bhonick** [comment]
@maxsibilla @libpitt If you could let me know when this is implemented, that would be great, thanks!

**Comment by maxsibilla** [comment]
@libpitt To proceed forward with this we should modify the current endpoint (`metadata/validate`) to expect a query parameter. This is how we will determine the metadata spec (current v2 or CEDAR) to validate against. The default with be to use the current spec just to be backwards compatible

**Comment by libpitt** [comment]
This tool https://metadatavalidator.metadatacenter.org/ is slightly not very user friendly. It is imperative that the user receives a link back.
![no user link](https://github.com/sennetconsortium/ingest-api/assets/115558393/fddef379-23f4-4d47-a7fe-53d420c397a0)

User given a Fix suggestion but no link back to where they need to go, HIVE website is not sufficient.

**Comment by libpitt** [comment]
### Testing CEDAR from the Portal:
**Can successfully hit CEDAR but still have a few issues, things to update:**
1. Need to update the logic that handles display of the error message to the user to handle the new keys like `Request Errors`, `Validation Errors` etc. (CEDAR response keys are different from legacy IVT response.)
2. In the `URL Errors` section, CEDAR complains of no token received. What token is this? The `get_tsv_errors` method only requires the `cedar_api_key`. Is this the airflow token? If so, how do we pass this?
3. CEDAR responds that the SenNet id is an invalid format. I reckon no support for the SenNet pattern ([SNT]+\d{3}\.[A-Za-z]{4}\.\d{3}) available. Worked when I used HuBMAP ids.

### Other / outside of task scope:
1. The IVT repo in addition to comment above, with same section name, from `examples/dataset-examples`, there is a mixing of cedar examples and legacy ones together. A developer/user with no knowledge that there are two systems in place may not immediately catch this. Ideally should have two additionally directories to clearly distinguish between testing tools. So can be: 
```
examples/dataset-examples/cedar
examples/dataset-examples/legacy
```

OR 
```
examples/cedar/dataset-examples
examples/legacy/dataset-examples
```

2. If users were using HuBMAP’s docs for preparing legacy tsv for validation, they are going to be so confused by the changes. There's no mention of the new system.

3. CEDAR validation: There is a fixSuggestion property in the validation response suggesting the user to download from HIVE website. Always a good idea to give the user a link so they find what they need.
![CEDAR example error](https://github.com/sennetconsortium/ingest-api/assets/115558393/4df429a5-4f2d-427d-ace0-d3297f8a984f)


cc @maxsibilla  @bhonick @shirey

**Comment by bhonick** [comment]
Thanks @libpitt for these points. I'm ask Josef Hardi (@johardi) from Stanford, the CEDAR developer, to add an allowance for IDs starting with either SNT or HBM.

**Comment by maxsibilla** [comment]
@libpitt One thing that I will have to test once we have CEDAR support for SenNet IDs is that all sub-fields inside `metadata` get indexed appropriately. One potential issue would be if a field inside the metadata that gets generated by CEDAR has a different data type from an existing metadata field of the same name.

**Comment by libpitt** [comment]
Thanks @maxsibilla and @bhonick 

**Can successfully hit CEDAR but still have a few issues, things to update:**
1. I am currently working on this point - https://github.com/sennetconsortium/portal-ui/issues/995
2. This was resolved and token is `groups_token` for reaching entity-api's /entities. Also had to add app context logic to generalize this for SN. Things were hard coded for HM
3. Thanks @bhonick for looking into this.

Another issue was noticed regarding schema name and assay type matching per column names. Was reported to @gesinaphillips for advice. 

```
Object { code: 500, description: "\n Assay type 'sample' does not match any assay type in\n enum '['Sample Block']' for schema /usr/src/app/src/routes/validation/ingest_validation_tools/src/ingest_validation_tools/table-schemas/others/sample-block-v2.yaml\n ", name: "Internal Server Error" }
```
