### ISSUE TITLE
Evaluate whether to update `verify_dataset_title_info` and `determine_sources_to_reindex` to use dataset_type

### ISSUE THREAD

**Issue by tjmadonna** [sennetconsortium/ingest-api#229]
`verify_dataset_title_info` and `determine_sources_to_reindex` both reference `data_types`. Both functions are not referenced in `ingest-api` and don't seem to be exposed to the outside.

`verify_dataset_title_info` also refernces the `SearchSdk` in `hubmap_sdk`. The comments say that it is the business logic for `/datasets/<uuid>/verifytitleinfo`. This endpoint exists on HuBMAP but not SenNet.

verify_dataset_title_info
https://github.com/sennetconsortium/ingest-api/blob/be1909e18a54164d7e13b5158a502e9bf31dbb7c/src/lib/dataset_helper.py#L69C18

determine_sources_to_reindex
https://github.com/sennetconsortium/ingest-api/blob/be1909e18a54164d7e13b5158a502e9bf31dbb7c/src/routes/entity_CRUD/dataset_helper.py#L359

**Comment by maxsibilla** [comment]
@tjmadonna `verify_dataset_title_info` is utilized in an endpoint that we do not expose (/datasets/<uuid>/verifytitleinfo). I would say that we can just remove this function as it clearly has not been used for SenNet. 

`determine_sources_to_reindex` doesn't even exist in the HuBMAP Ingest API and it isn't being called so we can also remove this function.
