### ISSUE TITLE
Coordinate with Gesina to get `subtype` from Cedar API call

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/ingest-api#233]
Currently when we validate metadata we have no way to ensure that the metadata file matches the Sample type via the portal. This branch (https://github.com/hubmapconsortium/ingest-validation-tools/commit/1f8a1605c6b14f6a83e3997fe68747faaa5f6df2) does not yet support returning from Cedar which subtype (e.g. Block, Suspension, Section) the metadata file was validated against.

**Comment by libpitt** [comment]
Also: 
https://github.com/sennetconsortium/ingest-validation-tools/pull/34#issuecomment-1836374367

Note for later:
`iv_utils.get_schema_version(upload.get('fullpath'), encoding='ascii', globus_token=get_groups_token())`

**Comment by libpitt** [comment]
Note this comment for later:

> Okay so [get_schema_version](https://github.com/hubmapconsortium/ingest-validation-tools/blob/dc3f13bfc53a4f668fa7eab7106af95abd1467cf/src/ingest_validation_tools/validation_utils.py#L37) should allow you to retrieve the more specific sample sub-type the same as any other schema. A sample would get diverted to [get_other_schema_name](https://github.com/hubmapconsortium/ingest-validation-tools/blob/dc3f13bfc53a4f668fa7eab7106af95abd1467cf/src/ingest_validation_tools/validation_utils.py#L92C5-L92C26) which reads the TSV and looks for a sample_id field (as well as unique fields for organ, contributors, and antibodies). If it finds a sample_id it looks for a type in the TSV and returns. It does assume there is a type field, so if that’s not always the case this is broken.
> This could use another guard against bad types, going to push a small update. Let me know if this has anything to do with what you’re hoping to accomplish or if you have any sanity checks about the logic.

**Comment by maxsibilla** [comment]
Calling `get_schema_version` with 
```
iv_utils.get_schema_version(<full_path>, "ascii", token)
```
returns something like this:
![image](https://github.com/sennetconsortium/ingest-api/assets/7218802/679db361-1701-48bd-a17e-4eb8165576c8)

Calling `get_other_schema_name` with 
```
iv_utils.get_other_schema_name(<get_schema_version.rows>, <full_path>)
```

Currently only returns "sample". I am unsure if this is how `schema_name` gets set in the return from `get_schema_version`. Is the response from `get_other_schema_name` being set to "sample" because of how this "other_types" is formatted? 
![image](https://github.com/sennetconsortium/ingest-api/assets/7218802/82f4ff83-bc64-48f4-bd06-67c54313ea5d)

**Comment by maxsibilla** [comment]
@libpitt it might be best for now to overload the existing `check_cedar` function to see if the passed in `sub_type` lines up with `metadata_schema_id`. Ideally this would be done in the IVT for every row but we can at least check the first row of data
