### ISSUE TITLE
Investigate whether neo4j connection needs closed after each request

### ISSUE THREAD

**Issue by tjmadonna** [sennetconsortium/ingest-api#390]
Having to reestablish a connection to neo4j on every request could add overhead. 

https://github.com/sennetconsortium/ingest-api/blob/b1884e66aaccf981bb0a99bd5b5b0503c1956665/src/app.py#L207

**Comment by maxsibilla** [comment]
@tjmadonna https://neo4j.com/docs/python-manual/current/connect/#_close_connections
```
Always close Driver objects to free up all allocated resources, even upon unsuccessful connection or runtime errors. Either instantiate the Driver object using the with statement, or call the Driver.close() method explicitly.
```

**Comment by tjmadonna** [comment]
I was taking a closer look at this and don't think this is a problem. The code first checks for a global Flask object `g` field called `neo4j_driver_instance`.  I can't find the place where this field is being set so I don't know if the driver is ever being closed.

https://github.com/sennetconsortium/ingest-api/blob/b1884e66aaccf981bb0a99bd5b5b0503c1956665/src/app.py#L205C5-L205C44
