### ISSUE TITLE
Handle file permissions for data/upload creation

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/ingest-api#485]
Currently in `app.cfg` we have the following configuration that is not be utilized:
```
GLOBUS_BASE_FILE_USER_NAME = ''
GLOBUS_ADMIN_FILE_USER_NAME = ''
GLOBUS_GENOMIC_DATA_FILE_GROUP_NAME = ''
GLOBUS_CONSORTIUM_FILE_GROUP_NAME = ''
```
These are currently being implemented here: https://github.com/sennetconsortium/ingest-api/blob/e8f3d6a0d02d173dfbd943909a1159993da06143/src/lib/ingest_file_helper.py#L130

The issue is that `setfacl` is not working against the AWS filesystem:
https://github.com/sennetconsortium/ingest-api/blob/e8f3d6a0d02d173dfbd943909a1159993da06143/src/lib/ingest_file_helper.py#L175

The directories and files within should have the permissions of `drwxr-x---` but currently set to `drwxr-xr-x`.

- [ ] All protected directories (all `Uploads` and protected datasets) need to be manually modified using the following command:

```
chmod 750 <dirname>
```

- [x] Remove the `GLOBUS_` properties and all instances in the code and modify the `setfacl` line to set the permissions as stated above

**Comment by libpitt** [comment]
Commenting this here for future: https://chmod-calculator.com/
