### ISSUE TITLE
Generate metadata.json files for processed datasets

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/ingest-api#490]
Currently metadata.json files are generated for primary datasets only, change this so metadata.json file are additionally generated for processed datasets where `creation_action == 'Central Process' or 'Lab Process' or 'External Process'` but not for multi-assay component datasets (component datasets match `creation_action == 'Multi-Assay Split`)

HM card: https://github.com/orgs/hubmapconsortium/projects/40/views/1?pane=issue&itemId=67730742

**Comment by libpitt** [comment]
We have this working here: [https://github.com/sennetconsortium/ingest-api/commit/a37f114138120fb80ab5608446874be72545142a#diff-dbbd81613f45e75c24d2[…]1a16b30b182368852c6eR1004](https://github.com/sennetconsortium/ingest-api/commit/a37f114138120fb80ab5608446874be72545142a#diff-dbbd81613f45e75c24d247a0a00eaf8bc018218b14771a16b30b182368852c6eR1004)

Verified after this card: https://github.com/sennetconsortium/ingest-api/issues/479
